import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { Action, Profile } from './domain';
import { SandboxProvider } from './integrations/sandbox-provider';
import { analyzeFinancialProfile } from './services/intelligence';
import { currency, prioritizeActions, scoreLabel } from './services/financial';
import './styles.css';

const provider = new SandboxProvider();
const nav = ['Dashboard', 'Financial profile', 'Accounts', 'Action plan', 'Goals', 'Insights', 'Settings'];
const today = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
function App() {
  const [profile, setProfile] = useState<Profile | null>(null); const [page, setPage] = useState('Dashboard'); const [online, setOnline] = useState(navigator.onLine); const [notice, setNotice] = useState('');
  useEffect(() => { provider.fetchProfile().then(setProfile); const on = () => setOnline(true); const off = () => setOnline(false); addEventListener('online', on); addEventListener('offline', off); return () => { removeEventListener('online', on); removeEventListener('offline', off); }; }, []);
  const metrics = useMemo(() => profile && analyzeFinancialProfile(profile), [profile]);
  const updateAction = (id: string, state: Action['state']) => { if (!profile) return; setProfile({ ...profile, actions: profile.actions.map((action) => action.id === id ? { ...action, state } : action) }); setNotice(state === 'done' ? 'Action marked complete.' : 'Action saved for later.'); };
  const refresh = () => provider.refreshData().then((next) => { setProfile(next); setNotice('Demo data refreshed.'); });
  const createGoal = () => { const name = window.prompt('Name your goal'); if (!name?.trim()) return; const target = Number(window.prompt('Target amount in GH₵')); if (!Number.isFinite(target) || target <= 0) { setNotice('Enter a valid positive target amount.'); return; } setProfile({ ...profile, goals: [...profile.goals, { id: crypto.randomUUID(), name: name.trim(), current: 0, target, unit: 'currency', due: 'Not scheduled' }] }); setNotice('Your goal has been created.'); };
  if (!profile || !metrics) return <main className="loading">Loading your financial picture…</main>;
  const actionList = prioritizeActions(profile.actions); const content = page === 'Dashboard' ? <Dashboard profile={profile} metrics={metrics} actions={actionList} updateAction={updateAction} setPage={setPage} /> : page === 'Financial profile' ? <ProfilePage profile={profile} metrics={metrics} refresh={refresh} /> : page === 'Accounts' ? <Accounts accounts={profile.accounts} refresh={refresh} /> : page === 'Action plan' ? <ActionPlan actions={actionList} updateAction={updateAction} /> : page === 'Goals' ? <Goals profile={profile} createGoal={createGoal} /> : page === 'Insights' ? <Insights profile={profile} setPage={setPage} /> : <Settings />;
  return <div className="app"><aside><a className="brand" href="#top"><span>↗</span> CreditFlow</a><p className="eyebrow">YOUR FINANCIAL SPACE</p><nav>{nav.map((item) => <button key={item} className={page === item ? 'active' : ''} onClick={() => setPage(item)}>{item}</button>)}</nav><div className="demo"><b>Demo mode</b><p>Simulated data only. No accounts are connected.</p></div></aside><main id="top"><header><div><p className="eyebrow">{today}</p><h1>{page}</h1></div><div className="header-actions"><span className={online ? 'connection' : 'connection offline'}>{online ? '● Online' : '● Offline'}</span><button className="avatar" aria-label="Open account settings" onClick={() => setPage('Settings')}>AB</button></div></header>{!online && <div className="offline-banner">You’re offline. Completed actions will stay on this device until you reconnect.</div>}{notice && <div className="toast">{notice}<button onClick={() => setNotice('')}>×</button></div>}{content}</main><nav className="mobile-nav">{nav.slice(0, 5).map((item) => <button className={page === item ? 'active' : ''} onClick={() => setPage(item)} key={item}>{item === 'Financial profile' ? 'Profile' : item}</button>)}</nav></div>;
}
function Dashboard({ profile, metrics, actions, updateAction, setPage }: { profile: Profile; metrics: ReturnType<typeof analyzeFinancialProfile>; actions: Action[]; updateAction: (id: string, state: Action['state']) => void; setPage: (page: string) => void }) { return <><section className="hero"><div><p className="eyebrow">FINANCIAL HEALTH</p><div className="score-line"><strong>{profile.score}</strong><div><b>{scoreLabel(profile.score)}</b><span>↑ {profile.score - profile.previousScore} this month</span></div></div><p>Steady habits are lifting your financial position.</p></div><div className="score-ring" aria-label={`${profile.score} out of 850`}><span>{profile.score}</span><small>/ 850</small></div></section><section className="metrics"><Metric label="Credit utilization" value={`${metrics.utilization.percentage}%`} caption={`${currency(metrics.utilization.used)} of ${currency(metrics.utilization.limits)} used`} tone="attention"/><Metric label="Payment history" value={`${metrics.paymentRate}%`} caption={`${profile.onTimePayments} on-time payments`} tone="good"/><Metric label="Available cash" value={currency(profile.accounts[1].balance)} caption="Savings balance" tone="neutral"/></section><section className="grid"><div><SectionTitle title="What needs your attention" link="View action plan" click={() => setPage('Action plan')}/><div className="stack">{actions.slice(0, 3).map((action) => <ActionCard key={action.id} action={action} update={updateAction}/>)}</div></div><div><SectionTitle title="Upcoming activity" link="View profile" click={() => setPage('Financial profile')}/><div className="card list">{profile.payments.map((p) => <div className="payment" key={p.id}><span className="date">{p.due}</span><div><b>{p.name}</b><small>{p.account}</small></div><strong>{currency(p.amount)}</strong><button aria-label={`Mark ${p.name} complete`} onClick={() => updateAction('ac2', 'done')}>✓</button></div>)}</div></div></section><section><SectionTitle title="Signals worth knowing" link="All insights" click={() => setPage('Insights')}/><div className="insights">{profile.insights.map((insight) => <article className="insight" key={insight.id}><span className={`priority ${insight.priority}`}>{insight.priority} priority</span><h3>{insight.title}</h3><p>{insight.detail}</p><button onClick={() => setPage(insight.action.includes('payoff') ? 'Action plan' : 'Financial profile')}>{insight.action} →</button></article>)}</div></section><p className="disclaimer">CreditFlow insights are educational and informational—not financial, legal, or credit-repair advice.</p></> }
function Metric({ label, value, caption, tone }: { label: string; value: string; caption: string; tone: string }) { return <article className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong><small>{caption}</small></article>; }
function SectionTitle({ title, link, click }: { title: string; link: string; click: () => void }) { return <div className="section-title"><h2>{title}</h2><button onClick={click}>{link} →</button></div>; }
function ActionCard({ action, update }: { action: Action; update: (id: string, state: Action['state']) => void }) { return <article className={`card action ${action.state !== 'open' ? 'muted' : ''}`}><span className={`priority ${action.impact}`}>{action.impact} impact</span><div><h3>{action.title}</h3><p>{action.detail}</p></div>{action.state === 'open' ? <div className="action-buttons"><button className="primary" onClick={() => update(action.id, 'done')}>Complete</button><button onClick={() => update(action.id, 'snoozed')}>Snooze</button></div> : <small>{action.state === 'done' ? 'Completed' : 'Snoozed'}</small>}</article> }
function ProfilePage({ profile, metrics, refresh }: { profile: Profile; metrics: ReturnType<typeof analyzeFinancialProfile>; refresh: () => void }) { return <><section className="profile-summary card"><div><p className="eyebrow">CURRENT FINANCIAL HEALTH</p><strong>{profile.score}</strong><span>{scoreLabel(profile.score)} · Up {profile.score - profile.previousScore} points this month</span></div><div className="trend"><i style={{ height: '38%' }}/><i style={{ height: '48%' }}/><i style={{ height: '55%' }}/><i style={{ height: '65%' }}/><i style={{ height: '74%' }}/><i style={{ height: '87%' }}/></div></section><section className="grid"><div className="card factor"><h2>Key factors</h2><Factor label="Payment history" value={`${metrics.paymentRate}% on time`} status="Strong"/><Factor label="Debt utilization" value={`${metrics.utilization.percentage}% used`} status="Needs attention"/><Factor label="Account age" value="4 years, 2 months" status="Established"/></div><div className="card utilization"><h2>Utilization & debt</h2><strong>{metrics.utilization.percentage}%</strong><p>{currency(metrics.utilization.used)} used of {currency(metrics.utilization.limits)} available credit.</p><div className="progress"><i style={{ width: `${metrics.utilization.percentage}%` }}/></div><small>Keeping revolving utilization below 30% may support a stronger financial profile.</small></div></section><Accounts accounts={profile.accounts} refresh={refresh}/></> }
function Factor({ label, value, status }: { label: string; value: string; status: string }) { return <div className="factor-row"><div><b>{label}</b><small>{value}</small></div><span>{status}</span></div>; }
function Accounts({ accounts, refresh }: { accounts: Profile['accounts']; refresh: () => void }) { return <section className="accounts"><SectionTitle title="Accounts" link="Refresh data" click={refresh}/><div className="account-grid">{accounts.map((account) => <article className="card account" key={account.id}><div><span className="bank-icon">{account.institution.slice(0, 1)}</span><span className="status">{account.status}</span></div><h3>{account.institution}</h3><p>{account.type}</p><strong>{currency(account.balance)}</strong>{account.limit && <small>{currency(account.limit)} credit limit</small>}<footer>Updated {account.updated}</footer></article>)}</div></section> }
function ActionPlan({ actions, updateAction }: { actions: Action[]; updateAction: (id: string, state: Action['state']) => void }) { return <><section className="plan-intro"><p className="eyebrow">PERSONALIZED, PRIORITIZED</p><h2>Your financial action plan</h2><p>Take the highest-impact step first. We use your demo account data to order these recommendations.</p></section><div className="plan-list">{actions.length ? actions.map((a, i) => <article className="plan-item" key={a.id}><span>0{i + 1}</span><ActionCard action={a} update={updateAction}/></article>) : <Empty title="You’re all caught up" detail="No active action items right now."/>}</div></> }
function Goals({ profile, createGoal }: { profile: Profile; createGoal: () => void }) { return <><SectionTitle title="Your financial goals" link="Create goal" click={createGoal}/><div className="goals">{profile.goals.map((goal) => { const percentage = goal.unit === 'percent' ? Math.min(100, Math.round(((100 - goal.current) / (100 - goal.target)) * 100)) : Math.min(100, Math.round((goal.current / goal.target) * 100)); return <article className="card goal" key={goal.id}><p className="eyebrow">TARGET · {goal.due}</p><h2>{goal.name}</h2><strong>{goal.unit === 'currency' ? currency(goal.current) : goal.current}{goal.unit === 'percent' ? '%' : ''}</strong><span>of {goal.unit === 'currency' ? currency(goal.target) : `${goal.target}${goal.unit === 'percent' ? '%' : ''}`}</span><div className="progress"><i style={{ width: `${percentage}%` }}/></div><small>{percentage}% of target reached</small></article>; })}</div></> }
function Insights({ profile, setPage }: { profile: Profile; setPage: (page: string) => void }) { return <><p className="plan-intro">Signals generated from your simulated accounts. They are educational and not financial advice.</p><div className="insights full">{profile.insights.map((insight) => <article className="insight card" key={insight.id}><span className={`priority ${insight.priority}`}>{insight.priority} priority</span><h3>{insight.title}</h3><p>{insight.detail}</p><button onClick={() => setPage(insight.action.includes('payoff') ? 'Action plan' : 'Financial profile')}>{insight.action} →</button></article>)}</div></> }
function Settings() { return <section className="card settings"><p className="eyebrow">DATA & PRIVACY</p><h2>Demo workspace</h2><p>This device is displaying simulated financial data from the CreditFlow sandbox provider. No bank connection, financial credential, or personal account data is stored.</p><h3>Connection status</h3><p>Sandbox provider active · ready for a credentialed provider adapter.</p></section> }
function Empty({ title, detail }: { title: string; detail: string }) { return <section className="empty"><h2>{title}</h2><p>{detail}</p></section>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
